# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'image-production-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'        
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'gateway-backend'
        regionName: 'us-east-2'
        imageSource: 'tag'
        sourceImageName: '$(tag)'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: 'gateway'        
        autoCreateRepository: true
        outputVariable: 'production'
