# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - develop

resources:
  - repo: self

variables:
  tag: "image-develop-$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              repository: $(tag)
          - task: ECRPushImage@1
            inputs:
              awsCredentials: "vileve-authentication"
              regionName: "us-east-1"
              imageSource: "imagename"
              sourceImageName: "$(tag)"
              sourceImageTag: "$(Build.BuildId)"
              repositoryName: "vileveway-backend"
              autoCreateRepository: true
              pushTag: "develop"
