const definitions = {
  Signin: {
    $email: "email@email.com.br",
    $senha: "string (shar256)",
  },
  SigninAdm: {
    $email: "email@email.com.br",
    $senha: "string (shar256)",
  },
  EditLog: {
    $level: "debug",
  },
  SignupCnpj: {
    usuario: {
      $nome: "nome",
      $email: "email@gmail.com",
      $senha: "shar256",
    },
    pessoa: {
      $cpf: "00000000000",
      $celular: "00000000000",
      $nascimento: "2021-01-01",
      $naturalidade: "Belorizontino",
      $nacionalidade: "Brasil",
      $estado_civil: "Solteiro",
      $rg: "MG00000000",
      $emissor: "SSP",
      $emissao: "2021-01-01",
      $sexo: "M",
      $mae: "Maria José de Oliveira",
      $pai: "Rubens de Oliveira",
    },
    empresa: {
      $cnpj: "000000000000000",
      $cnae: 0,
      $razao_social: "Empresa Exemplo ltda",
      $telefone_fixo: "0000000000",
      $celular: "00000000000",
      $nome_fantasia: "Nome Fantasia",
      $site: "https://www.site.com.br",
    },
    conta: {
      $banco: "NuBank",
      $agencia: "0000",
      $conta: "00000000000",
      $operacao: "Número da operação (caso tenha)",
      $pix: "pix",
    },
    endereco_cnpj: {
      $cep: "00000000",
      $endereco: "Rua fictícia",
      $complemento: "202",
      $numero: "71",
      $bairro: "Centro",
      $cidade: "Curvelo",
      $estado: "MG",
    },
    endereco_cpf: {
      $cep: "00000000",
      $complemento: "",
      $endereco: "Rua fictícia",
      $numero: "71",
      $bairro: "Centro",
      $cidade: "Curvelo",
      $estado: "MG",
    },
  },
  SignupCpf: {
    usuario: {
      $nome: "nome",
      $email: "email@gmail.com",
      $senha: "shar256",
    },
    pessoa: {
      $cpf: "00000000000",
      $celular: "00000000000",
      $nascimento: "2021-01-01",
      $naturalidade: "Belorizontino",
      $nacionalidade: "Brasil",
      $estado_civil: "Solteiro",
      $rg: "MG00000000",
      $emissor: "SSP",
      $emissao: "2021-01-01",
      $sexo: "M",
      $mae: "Maria José de Oliveira",
      $pai: "Rubens de Oliveira",
    },
    conta: {
      $banco: "NuBank",
      $agencia: "0000",
      $conta: "00000000000",
      $operacao: "Número da operação (caso tenha)",
      $pix: "pix",
    },
    endereco_cpf: {
      $cep: "00000000",
      $complemento: "",
      $endereco: "Rua fictícia",
      $numero: "71",
      $bairro: "Centro",
      $cidade: "Curvelo",
      $estado: "MG",
    },
  },
  DocumentsUpload: {
    $idClient: 1,
    $product: "vilevewayclient",
    $itens: [
      {
        categorie: "comprovante_de_residencia",
        filename: "comprovante_de_residencia.png",
      },
      {
        categorie: "cartao_cnpj",
        filename: "cartao_cnpj.png",
      },
    ],
  },
  Group: {
    $nome: "Administração",
  },
  UserGroup: [
    {
      $fk_id_usu_adm: 10,
      $fk_id_grupo: 1,
    },
    {
      $fk_id_usu_adm: 10,
      $fk_id_grupo: 2,
    },
    {
      $fk_id_usu_adm: 10,
      $fk_id_grupo: 1,
    },
    {
      $fk_id_usu_adm: 10,
      $fk_id_grupo: 3,
    },
    {
      $fk_id_usu_adm: 10,
      $fk_id_grupo: 2,
    },
  ],
  PersonCellphone: {
    $celular: 00000000000,
  },
  ShopkeepersEdit: {
    usuario: {
      $id: 10,
      $nome: "nome",
      $email: "email@gmail.com",
      $senha: "shar256",
    },
    pessoa: {
      $id: 10,
      $cpf: "00000000000",
      $celular: "00000000000",
      $nascimento: "2021-01-01",
      $naturalidade: "Belorizontino",
      $nacionalidade: "Brasil",
      $estado_civil: "Solteiro",
      $rg: "MG00000000",
      $emissor: "SSP",
      $emissao: "2021-01-01",
      $sexo: "M",
      $mae: "Maria José de Oliveira",
      $pai: "Rubens de Oliveira",
    },
    empresa: {
      $id: "cnpj",
      $cnpj: "000000000000000",
      $cnae: 0,
      $razao_social: "Empresa Exemplo ltda",
      $telefone_fixo: "0000000000",
      $celular: "00000000000",
      $nome_fantasia: "Nome Fantasia",
      $site: "https://www.site.com.br",
    },
    conta: {
      $id: "cnpj",
      $banco: "NuBank",
      $agencia: "0000",
      $conta: "00000000000",
      $operacao: "Número da operação (caso tenha)",
      $pix: "pix",
    },
    endereco_cnpj: {
      $id: "cnpj",
      $cep: "00000000",
      $endereco: "Rua fictícia",
      $complemento: "202",
      $numero: "71",
      $bairro: "Centro",
      $cidade: "Curvelo",
      $estado: "MG",
    },
    endereco_cpf: {
      $cpf: "cpf",
      $cep: "00000000",
      $complemento: "",
      $endereco: "Rua fictícia",
      $numero: "71",
      $bairro: "Centro",
      $cidade: "Curvelo",
      $estado: "MG",
    },
    tarifa: {
      $id: 10,
      $risco: "alto",
      $periodo: "Mensal",
      $observacao: "Obs",
      $segmento: "Segmentos",
      $tipo_cobranca: "Fixo",
      $faturamento: 50,
      $cobranca: 555,
    },
  },
  CreateUserAdm: {
    $nome: "Nome do usuário",
    $email: "email@email.com",
    $status: "ATIVO",
  },
  EditUserAdm: {
    $nome: "Nome do usuário",
    $email: "email@email.com",
    $status: "ATIVO",
  },
  EmailInvatation: {
    $id: 147,
    $name: "Nome do usuário",
    $status: "ATIVO",
  },
  FinisheRegister: {
    $id: "10",
    $nome: "Nome do usuário",
    $email: "email@email.com",
    $cpf: "000.000.000-00",
    $celular: "31-99999-9999",
    $ramal: "9999",
  },
};

module.exports = {
  definitions,
};
